### ISSUE TITLE
Remake Menu buttons

### ISSUE THREAD

**Issue by Verpad** [Verpad/BFL#49]
- [x] Replace existing menu image-buttons with new text-ones with updated design.
- [x] Add simple sound effects to buttons and menu music

**Comment by Verpad** [comment]
Hmm, I want to implement some simple audio effects in this task as well, is it ok?

**Comment by weterbogov** [comment]
@Verpad I think it is better to create separate task for this, but if this sound will be svery simply ist is ok

**Comment by Verpad** [comment]
Changed buttons style and added some simple animation. Check this out!

![menu](https://user-images.githubusercontent.com/15237465/43464927-eb5e6b8c-94e4-11e8-9af2-4bf67af18d8e.gif)
