### ISSUE TITLE
Make simple models of structures

### ISSUE THREAD

**Issue by Verpad** [Verpad/BFL#5]
### Create simple models of common structures, such as:

- [x] **Town hall** (Main central building)
- [x] **Barracks** (Used to produce military units)
- [x] **House** (Commonly used to increase max unit count)

**Comment by SuperioGreatK** [comment]
![image](https://user-images.githubusercontent.com/27236202/43796585-565147ea-9a8d-11e8-9c3b-a22927849c0a.png)

![image](https://user-images.githubusercontent.com/27236202/43796710-b6871b12-9a8d-11e8-9c00-ecb9f054e5f5.png)
![image](https://user-images.githubusercontent.com/27236202/43796722-bf3d0352-9a8d-11e8-98bb-62971dc2d177.png)

![image](https://user-images.githubusercontent.com/27236202/43797296-9b1c449a-9a8f-11e8-9456-0947352377c9.png)
![image](https://user-images.githubusercontent.com/27236202/43797303-a20a7768-9a8f-11e8-9527-d0de2d4a354d.png)

**Comment by Verpad** [comment]
@weterbogov pls review new models

**Comment by weterbogov** [comment]
@Verpad it is ok
